name: Build and Test Plugin
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java:
          - 21
    name: Build and Test Plugin Template
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Build and Run Tests
      run: |
        ./gradlew build
